<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="2" hostname="HDC3-L-01FDU7" name="seleniumTestNG.IretryAnalyser1" tests="3" failures="1" timestamp="27 Jul 2019 07:18:22 GMT" time="0.023" errors="0">
  <testcase name="hardAssertion" time="0.001" classname="seleniumTestNG.IretryAnalyser1">
    <failure type="java.lang.AssertionError" message="expected [null] but found [assertion]">
      <![CDATA[java.lang.AssertionError: expected [null] but found [assertion]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotSame(Assert.java:772)
at org.testng.Assert.assertNull(Assert.java:708)
at org.testng.Assert.assertNull(Assert.java:697)
at seleniumTestNG.IretryAnalyser1.hardAssertion(IretryAnalyser1.java:35)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- hardAssertion -->
  <testcase name="hardAssertion" time="0.001" classname="seleniumTestNG.IretryAnalyser1">
    <skipped/>
  </testcase> <!-- hardAssertion -->
  <testcase name="hardAssertion" time="0.021" classname="seleniumTestNG.IretryAnalyser1">
    <skipped/>
  </testcase> <!-- hardAssertion -->
</testsuite> <!-- seleniumTestNG.IretryAnalyser1 -->
